version: '3'

services:
  djangoapp:
   build: .
   volumes:
      - .:/home/project
      - static_volume:/home/project/personalweb/static
   networks:  # <-- here
      - nginx_network
   
  nginx:
   image: nginx:latest   
   ports:
      - 8080:80
   volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/home/project/personalweb/static
   depends_on:
      - djangoapp
   networks:  # <-- here
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  
volumes:
   static_volume:

